apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-npzzvdhg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-npzzvdhg:940ffc2428c020c1c823dd60a066246e62a9409e@sha256:a8527e40573cd1ecc50b046c7618bd5a5e8404e5ca2f88c5838ff1f38a5ee18e
          name: container-image
