apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-npzzvdhg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-npzzvdhg:9c85e7c3162eac6827a503677239ea7019244dc7@sha256:ec6d2d8762923a444437cd4a273856aef2edc271e007716882d7569ff9c461f6
          name: container-image
